name: duelinmarkers.com
url: http://www.duelinmarkers.com
timezone: America/Chicago
exclude: [Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
gems:
  - jekyll-feed